# DataBase mysql

version: "8.3"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_DB: tripPlanner
      MYSQL_PASSWORD: root


  trip:
      image: tripPlanner/trip-api   
      ports:
        - "8081:8081"
      environment:
        MYSQL_URL: jdbc:mysql://localhost:3306/trip
        MYSQL_USER: root
        MYSQL_PASSWORD: root
  depends_on:
        - mysql

  participant:
      image: tripPlanner/participant-api   
      ports:
        - "8082:8082"
      environment:
        MYSQL_URL: jdbc:mysql://localhost:3306/participant
        MYSQL_USER: root
        MYSQL_PASSWORD: root
  depends_on:
        - mysql

  link:
      image: tripPlanner/link-api   
      ports:
        - "8083:8083"
      environment:
        MYSQL_URL: jdbc:mysql://localhost:3306/link
        MYSQL_USER: root
        MYSQL_PASSWORD: root
  depends_on:
        - mysql

  activity:
      image: tripPlanner/activity-api    
      ports:
        - "8084:8084"
      environment:
        MYSQL_URL: jdbc:mysql://localhost:3306/activity
        MYSQL_USER: root
        MYSQL_PASSWORD: root
  depends_on:
        - mysql

  accommodation:
      image: tripPlanner/accommodation-api    
      ports:
        - "8085:8085"
      environment:
        MYSQL_URL: jdbc:mysql://localhost:3306/accommodation
        MYSQL_USER: root
        MYSQL_PASSWORD: root
  depends_on:
        - mysql